### ISSUE TITLE
User-can-see-their-car

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a parent div in the body of the html page for the img element
- [x] find the right src value for the img element
- [x] size the img appropriately
- [x] Set the background color of the body to green
- [x] Set the margin of the body to 0 so the car is flush against the edge of the page
- [x] Remove all CSS styling that did not have an effect
- [x] Test all functionality again in a private browser
- [x] Fix all errors
