### ISSUE TITLE
User-can-turn-their-car

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add a class to the car for styling purposes
- [x] create css styling that changes the orientation of the car
- [x] create a keydown event listener that changes the orientation of the car based on the key struck
- [x] remove any excess CSS
- [x] fix all errors
