### ISSUE TITLE
User-can-start-their-car

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] change the position of the image to absolute
- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use the style property of the element to change your car's top and left box offset styles.
- [x] car should move forward every 16 milliseconds
- [x] fix all errors and remove unnecessary CSS
