### ISSUE TITLE
User-can-stop-their-car

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add a boolean value to the data model indicating if the car has started or not.
- [x] add an event listener for the spacebar 
- [x] create a function that will stop the forward progression of the car if the spacebar is hit
- [x] hitting the space bar should be able to start and stop the car
- [x] fix any errors or unnecessary CSS styling
